# Generated by Django 3.1.2 on 2022-01-27 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220127_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='vaction_id',
            new_name='vacation_id',
        ),
    ]
