# Generated by Django 3.1.2 on 2022-01-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Activities',
        ),
        migrations.RenameField(
            model_name='activities',
            old_name='vacations',
            new_name='vacation',
        ),
    ]
